apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  type: {{ .Values.service.type }}
